/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.DAOConsulta;
import DAO.DAOConsultasAgendadas;
import Modelo.*;
import Dados.*;
import Impressao.CriarArquivoDeImpressao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author msa04
 */
public class TelaMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaMedico
     */
    private Medico medico;
    private int aprovado = 0;
    
    public TelaMedico(Medico medico) {
        this.medico = medico;
        Dados.pegarDados();
        initComponents();
        aprovado = 1;
        getContentPane().setBackground(Color.WHITE);
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public void converterVectorConsulta() {
        ArrayList<ConsultasAgendadas> lista = Dados.ListaDeConsultasAgendadas;
        String[] listaDeNomes = new String[lista.size()];
            int y = 0;
        for (int i = 0; i <= lista.size() - 1; i++) {
            ConsultasAgendadas cc = lista.get(i);
            if (cc.getMedicoResponsavel().getIdMedico() == this.medico.getIdMedico()) {
                listaDeNomes[y] = ("Consulta: " + cc.getNomeConsulta() + " ("
                        + cc.getDiaConsulta() + "/" + cc.getMesConsulta() + "/"
                        + cc.getAnoConsulta() + "   -   " + cc.getHoraConsulta() + ":"
                        + cc.getMinutosConsulta() + ")"
                        + ": Paciente: " + cc.getPacienteAcompanhado().getNome() + " "
                        + cc.getPacienteAcompanhado().getIdPaciente()
                        + "; ("
                        + cc.getIdConsultaAgendada() + ")");
                
            jComboBox2.addItem(listaDeNomes[y]);
                y++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela do mÃ©dico");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Consulta");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(237, 237, 237));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(237, 237, 236));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Midia/Config.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        converterVectorConsulta();

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 425));

        jToolBar3.setBackground(new java.awt.Color(237, 237, 237));
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jButton5.setBackground(new java.awt.Color(237, 237, 237));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Midia/$RYL8V8P.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton5);

        jButton4.setBackground(new java.awt.Color(237, 237, 237));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Midia/newImpressora.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton4);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        if(aprovado == 1){
            PreencherMedicacao();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Dados gerais do paciente");

        jLabel3.setText("Nome:");

        jt1.setEditable(false);
        jt1.setBackground(new java.awt.Color(244, 244, 244));
        jt1.setBorder(null);

        jt2.setEditable(false);
        jt2.setBackground(new java.awt.Color(244, 244, 244));
        jt2.setBorder(null);

        jLabel4.setText("CPF:");

        jt3.setEditable(false);
        jt3.setBackground(new java.awt.Color(244, 244, 244));
        jt3.setBorder(null);

        jLabel5.setText("Telefone:");

        jt4.setEditable(false);
        jt4.setBackground(new java.awt.Color(244, 244, 244));
        jt4.setBorder(null);

        jLabel6.setText("Idade:");

        jt5.setEditable(false);
        jt5.setBackground(new java.awt.Color(244, 244, 244));
        jt5.setBorder(null);
        jt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cidade:");

        jt6.setEditable(false);
        jt6.setBackground(new java.awt.Color(244, 244, 244));
        jt6.setBorder(null);

        jLabel8.setText("Bairro:");

        jt7.setEditable(false);
        jt7.setBackground(new java.awt.Color(244, 244, 244));
        jt7.setBorder(null);

        jLabel9.setText("Rua:");

        jt8.setEditable(false);
        jt8.setBackground(new java.awt.Color(244, 244, 244));
        jt8.setBorder(null);

        jLabel10.setText("NÃºmero:");

        jLabel11.setText("Dados pessoais");

        jLabel12.setText("EndereÃ§o");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt5)
                    .addComponent(jt6)
                    .addComponent(jt7)
                    .addComponent(jt8)
                    .addComponent(jt1)
                    .addComponent(jt2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jt3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jt4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja concluir, salvar e imprimir a consulta?");
        if (confirmacao == JOptionPane.OK_OPTION) {

            String cod = "";
            int i = 0;
            for (i = jComboBox2.getSelectedItem().toString().length() - 2; !((jComboBox2.getSelectedItem().toString().charAt(i) + "").equals("(")); i--) {
                cod = jComboBox2.getSelectedItem().toString().charAt(i) + cod;
            }
            ConsultasAgendadas cc = new ConsultasAgendadas();
            for (int o = 0; o <= Dados.getListaDeConsultasAgendadas().size() - 1; o++) {
                if (Dados.getListaDeConsultasAgendadas().get(o).getIdConsultaAgendada() == Integer.parseInt(cod)) {
                    cc = Dados.getListaDeConsultasAgendadas().get(o);
                }
            }

            CriarArquivoDeImpressao imprimir = new CriarArquivoDeImpressao(cc, jTextArea1.getText(), false);

            boolean ok = imprimir.getOk();
            if (ok) {
                Consulta c = new Consulta(jTextArea1.getText(), cc.getNomeConsulta(),
                        cc.getDiaConsulta(), cc.getMesConsulta(), cc.getAnoConsulta(),
                        cc.getHoraConsulta(), cc.getMinutosConsulta(), cc.getMedicoResponsavel(),
                        cc.getPacienteAcompanhado());
                
                DAOConsulta.salvar(c);
                DAOConsultasAgendadas.remover(cc);
            }

            TelaMedico t = new TelaMedico(this.medico);
            t.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja concluir e salvar a consulta?");
        if (confirmacao == JOptionPane.OK_OPTION) {
            String cod = "";
            int i = 0;
            for (i = jComboBox2.getSelectedItem().toString().length() - 2; !((jComboBox2.getSelectedItem().toString().charAt(i) + "").equals("(")); i--) {
                cod = jComboBox2.getSelectedItem().toString().charAt(i) + cod;
            }
            ConsultasAgendadas cc = new ConsultasAgendadas();
            for (int o = 0; o <= Dados.getListaDeConsultasAgendadas().size() - 1; o++) {
                if (Dados.getListaDeConsultasAgendadas().get(o).getIdConsultaAgendada() == Integer.parseInt(cod)) {
                    cc = Dados.getListaDeConsultasAgendadas().get(o);
                }
            }
            CriarArquivoDeImpressao imprimir = new CriarArquivoDeImpressao(cc, jTextArea1.getText(), true);
            boolean ok = imprimir.getOk();
            if (ok) {
                Consulta c = new Consulta(jTextArea1.getText(), cc.getNomeConsulta(),
                        cc.getDiaConsulta(), cc.getMesConsulta(), cc.getAnoConsulta(),
                        cc.getHoraConsulta(), cc.getMinutosConsulta(), cc.getMedicoResponsavel(),
                        cc.getPacienteAcompanhado());
                
                DAOConsulta.salvar(c);
                DAOConsultasAgendadas.remover(cc);
            }
            TelaMedico t = new TelaMedico(this.medico);
            t.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ConfigMedico config = new ConfigMedico(this.medico);
        config.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String cod = "";
        int i = 0;
        for (i = jComboBox2.getSelectedItem().toString().length() - 2; !((jComboBox2.getSelectedItem().toString().charAt(i) + "").equals("(")); i--) {
            cod = jComboBox2.getSelectedItem().toString().charAt(i) + cod;
        }
        ConsultasAgendadas cc = new ConsultasAgendadas();
        for (int o = 0; o <= Dados.getListaDeConsultasAgendadas().size() - 1; o++) {
            if (Dados.getListaDeConsultasAgendadas().get(o).getIdConsultaAgendada() == Integer.parseInt(cod)) {
                cc = Dados.getListaDeConsultasAgendadas().get(o);
            }
        }
        Paciente p = cc.getPacienteAcompanhado();
        jt1.setText(p.getNome());
        jt2.setText(p.getCPF());
        jt3.setText(p.getTelefone());
        jt4.setText(Integer.toString(p.getIdade()));
        jt5.setText(p.getCidade());
        jt6.setText(p.getBairro());
        jt7.setText(p.getRua());
        jt8.setText(Integer.toString(p.getNumeroDaCasa()));
        PreencherMedicacao();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    // End of variables declaration//GEN-END:variables

    public Medico getMedico() {
        return medico;
    }

    public void setMedico(Medico medico) {
        this.medico = medico;
    }

    private void PreencherMedicacao() {
        String cod = "";
        int i = 0;
        for (i = jComboBox2.getSelectedItem().toString().length() - 2; !((jComboBox2.getSelectedItem().toString().charAt(i) + "").equals("(")); i--) {
            cod = jComboBox2.getSelectedItem().toString().charAt(i) + cod;
        }
        ConsultasAgendadas cc = new ConsultasAgendadas();
        for (int o = 0; o <= Dados.getListaDeConsultasAgendadas().size() - 1; o++) {
            if (Dados.getListaDeConsultasAgendadas().get(o).getIdConsultaAgendada() == Integer.parseInt(cod)) {
                cc = Dados.getListaDeConsultasAgendadas().get(o);
            }
        }
        jTextArea1.setText("\nRECEITA MÃ‰DICA    -    CLÃ�NICA MSA\n\n"
                + "Dados do Paciente:\n"
                + cc.getPacienteAcompanhado().toString() + "\n\n"
                + "Dados da Conculta:\n"
                + cc.toString() + "\n\n"
                + "Dados do MÃ©dico:\n"
                + cc.getMedicoResponsavel().toString() + "\n\n"
                + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
                + "ASSINATURA DO MÃ‰DICO:\n\n"
                + "_______________________________________________\n\n");
        
     }

    public int getAprovado() {
        return aprovado;
    }

    public void setAprovado(int aprovado) {
        this.aprovado = aprovado;
    }
}
